# Exp_1. Numpy API

In [1]:
from platform import python_version

In [2]:
print(python_version())

3.8.8


In [3]:
import sys
print(sys.version)

3.8.8 (default, Apr 13 2021, 15:08:03) [MSC v.1916 64 bit (AMD64)]


# Check NumPy Version

In [4]:
import numpy
numpy.__version__

'1.19.5'

In [5]:
# conda list

# numerical python

In [6]:
import numpy as np

In [8]:
x = [1, 2, 3, 4, 5]
print(type(x))
print(len(x))
len(x)

<class 'list'>
5


5

In [9]:
x1 = [[1, 2, 3, 4], [5, 6, 7, 8]]
print(type(x1))
print(len(x1))

<class 'list'>
2


In [12]:
X1 = np.array(x1, dtype=np.double)
X1.shape

(2, 4)

In [13]:
y1 = np.array([
    [9, 8, 7, 6],
    [1, 3, 5, 7]
], dtype=np.float16)
print(X1 - y1)

[[-8. -6. -4. -2.]
 [ 4.  3.  2.  1.]]


# creating 1D arrays with functions

In [18]:
x = np.arange(1, 50, 5, dtype=np.uint)
print(x)
print(type(x))

[ 1  6 11 16 21 26 31 36 41 46]
<class 'numpy.ndarray'>


In [21]:
x = np.linspace(1, 9, 80)
print(x)

[1.         1.10126582 1.20253165 1.30379747 1.40506329 1.50632911
 1.60759494 1.70886076 1.81012658 1.91139241 2.01265823 2.11392405
 2.21518987 2.3164557  2.41772152 2.51898734 2.62025316 2.72151899
 2.82278481 2.92405063 3.02531646 3.12658228 3.2278481  3.32911392
 3.43037975 3.53164557 3.63291139 3.73417722 3.83544304 3.93670886
 4.03797468 4.13924051 4.24050633 4.34177215 4.44303797 4.5443038
 4.64556962 4.74683544 4.84810127 4.94936709 5.05063291 5.15189873
 5.25316456 5.35443038 5.4556962  5.55696203 5.65822785 5.75949367
 5.86075949 5.96202532 6.06329114 6.16455696 6.26582278 6.36708861
 6.46835443 6.56962025 6.67088608 6.7721519  6.87341772 6.97468354
 7.07594937 7.17721519 7.27848101 7.37974684 7.48101266 7.58227848
 7.6835443  7.78481013 7.88607595 7.98734177 8.08860759 8.18987342
 8.29113924 8.39240506 8.49367089 8.59493671 8.69620253 8.79746835
 8.89873418 9.        ]


# arange doesnot control the number of items it has step size and linspace has items.
# 2D Arrays

# 2D identify matrix

In [22]:
x = np.eye(2)
print(x)
print(np.eye(3, 5))

[[1. 0.]
 [0. 1.]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


# diagonal matrix

In [27]:
x = np.diag([2, 3, 4], -2)   # Replace 0 with +1 and -1
print(x)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [2 0 0 0 0]
 [0 3 0 0 0]
 [0 0 4 0 0]]


# generation of linear least squares models.

In [28]:
x = np.vander([1, 2, 3, 4], 5)
print(x)

[[  1   1   1   1   1]
 [ 16   8   4   2   1]
 [ 81  27   9   3   1]
 [256  64  16   4   1]]


# matrix of one's, zeros and randoms

In [31]:
x = np.ones((3, 3))
print(x)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [30]:
x = np.zeros((3, 2))
print(x)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


# Random Number Generator using Numpy

In [32]:
from numpy.random import default_rng

In [34]:
x = default_rng(22).random((2, 3)) # Change 0 to 42 or any other like 6
print(x)

[[0.36634692 0.19929538 0.08855837]
 [0.65319169 0.45933704 0.98767562]]


# index matrix

In [35]:
x = np.indices((1,2))
#x = np.indices((2,3))
#x = np.indices((3,3))
#x = np.indices((1,3))
print(x)

[[[0 0]]

 [[0 1]]]


# operations on arrays

In [40]:
a = np.array([1, 2, 3, 4, 5, 6])
b = a[3:4].copy()
b *= 10 # b = b*10
print(b)

[40]


In [38]:
index = np.where(a)[0] # type 1 in place of 0
index

array([0, 1, 2, 3, 4, 5], dtype=int64)

# joining pre defined arrays

In [41]:
a = np.array([1, 2, 3, 4])
b = np.eye(4, 4)
print(np.hstack(b))
print(np.vstack(a))

[1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1.]
[[1]
 [2]
 [3]
 [4]]


In [42]:
C1 = np.eye(2, 2)
C2 = np.ones((2, 2))
C3 = np.zeros((2, 2))
C4 = np.diag((3, 4))
B = np.block([[C1, C2], [C3, C4]])
print(B)

[[1. 0. 1. 1.]
 [0. 1. 1. 1.]
 [0. 0. 3. 0.]
 [0. 0. 0. 4.]]


# array indexing

In [43]:
x = np.arange(10)
print(x)
print(x[2])  # forward index
print(x[-2])  # reverse indexing

[0 1 2 3 4 5 6 7 8 9]
2
8


In [45]:
x = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
print(x.shape)
print(x[-1, -2])
print(x[:3, :1])

(3, 3)
8
[[1]
 [4]
 [7]]


# """slicing and striding """

In [46]:
x = np.arange(10)
print(x[1:9:2])
print(x[-1:-9:-2])
print(x[-2:10])
print(x[-3:3:-1])
print(x[5:])

[1 3 5 7]
[9 7 5 3]
[8 9]
[7 6 5 4]
[5 6 7 8 9]


# for loop 

In [47]:
X = [1, 2, 3]
Z = [4, 5, 6]
y = [a + b * 2 for a, b in zip(X, Z)]
print(y)
print(np.zeros_like(X))
print(np.ones_like(X))
print(np.empty_like(X))
print(np.full_like(X, 3))

[9, 12, 15]
[0 0 0]
[1 1 1]
[1 2 3]
[3 3 3]


# sequences generators

In [ ]:
print(np.arange(3))
print(np.arange(1, 6))
print(np.arange(1., 6., 2))
print(np.linspace(1, 6, 4))

# linspace s,s,no.of items
# arange s,s,gap between items

In [ ]:
rng = np.random.default_rng()
print(rng.integers(0, 9, 3))  # excluding 9
print(rng.integers(0, 9, 3, endpoint=True))  # include 9
print(rng.random(3))
print(rng.standard_normal(3))
print(rng.uniform(0, 7, 2))
print(rng.normal(5, 2, 3))

mean 5, var 2
# indexing of Arrays

In [ ]:
a = np.arange(0, 6)
print(a)
print(a[2])
print(a[2:4])
print(a[-3:])
print(a[::-2])
print(a[2::])
print(a[:2:])
b = a.copy()
print(b[:])

# Arrays are mutable meaning that they can be modified

# BOOLEAN INDEXING

In [48]:
a = np.array([1, 2, 5, 8, 4, 9, 3])
b = a > 5
b = np.any(a > 5)
b = np.all(a > 5)
print(b)

False


# indexing Boolean to extract values

In [ ]:
print(a[a > 5])
a[a > 5] = 0
print(a)

In [ ]:
a = np.array([1, 2, 4, 5, 7, 3, 9, 2])
a[(a >= 3) & (a <= 5)] = 0
print(a)

In [ ]:
a = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
    [13, 14, 15, 16]
])
print(a.shape)
print(a[:4])

# the meaning of colon in
# arrays or lists is copy

In [ ]:
a = np.array([1, 2, 3, 4, 5, 3, 4, 6, 7, 8, 4])
print(np.where(a > 3))
print(np.nonzero(a > 4))
print(len(a))

# math operations on arrays

In [ ]:
a = np.array([1, 2])
b = np.array([3, 4])
print(a + b)
print(a - b)
print(a * b)
print(a / b)
print(a // b)
print(a ** b)

In [ ]:
print(np.sqrt(a))
print(np.exp(a))
print(np.log(a))
print(np.dot(a, b))
print(np.cross(a, b))

# Strings

In [ ]:
s = "hello"

In [ ]:
print(s.capitalize())  # Capitalize a string; prints "Hello"
print(s.upper())       # Convert a string to uppercase; prints "HELLO"
print(s.rjust(7))      # Right-justify a string, padding with spaces; prints "  hello"
print(s.center(7))     # Center a string, padding with spaces; prints " hello "
print(s.replace('l', '(ell)'))  # Replace all instances of one substring with another;
                                # prints "he(ell)(ell)o"
print('  world '.strip())  # Strip leading and trailing whitespace; prints "world"

In [ ]:
birds = ['hen', 'pegion', 'parrot','peacock','duck']
for bird in birds:
    print(bird) # Try birds

# Lists

In [ ]:
xs = [3, 1, 2]    # Create a list
print(xs, xs[2])  # Prints "[3, 1, 2] 2"

In [ ]:
print(xs[-1])     # Negative indices count from the end of the list; prints "2"

In [ ]:
xs[2] = 'Mlwp'     # Lists can contain elements of different types
print(xs)         

In [ ]:
xs.append('python')  # Add a new element to the end of the list
print(xs)         

In [ ]:
x = xs.pop()      # Remove and return the last element of the list
print(x, xs)      

# Slicing on lists

In [ ]:
a_list = list(range(8))     # range is a built-in function that creates a list of integers

In [ ]:
print(a_list)

In [ ]:
print(a_list[2:4])          # Get a slice from index 2 to 4 (exclusive); prints "[2, 3]"
print(a_list[2:])           # Get a slice from index 2 to the end; prints "[2, 3, 4]"
print(a_list[:2])           # Get a slice from the start to index 2 (exclusive); prints "[0, 1]"
print(a_list[:])            # Get a slice of the whole list; prints "[0, 1, 2, 3, 4]"
print(a_list[:-1])          # Slice indices can be negative; prints "[0, 1, 2, 3]"

In [ ]:
a_list[2:4] = [9, 10]        # Assign a new sublist to a slice
print(a_list)           

# Weekly Assesment Questions - Submit using this one drive link. 

https://kluniversityin-my.sharepoint.com/:f:/g/personal/pvvkishore_kluniversity_in/EsKd3jmPbHtFreSilPrPG6YB5Mpt7UfgF8Ee_p3LBeNiwg?e=9WM7DT

# File Name Should be: RollNo_WANo

# 1. Construct a list of 50 floating point numbers and find the square root on the list. Convert the list into a numpy intiger array.

# 2. Construct a list of 10 contineous numbers and swap the first and last elements of the list.

# 3. Construct two arrays of random numbers and perform all the mathmatical operations on these two arrays.