In [1]:
import numpy as np
import pandas as pd
#import keras
import tensorflow as tf

In [2]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten
from tensorflow.keras.layers import LSTM, GRU, SimpleRNN
from tensorflow.keras.layers import Embedding

In [3]:
data = """ Tab Rasode me kaun tha\n
		Tum thi ? mai thi?kaun tha?\n
		Rashi Thi\n
		Tab Rashi ne Kuckar me se chanee nikal diyaa
		aur kahlee kucker gas pe chadd diyaa\n """

In [4]:
data3 = """ Jack and Jill went up the hill\n
		To fetch a pail of water\n
		Jack fell down and broke his crown\n
		And Jill came tumbling after\n """

In [5]:
data1 = ['How are you today',
         'What are you doing today',
         'How is your day today',
         'What are your plans today']

In [6]:
data2 = ['Well done!',
		'Good work',
		'Great effort',
		'nice work',
		'Excellent!']

In [7]:
data3

' Jack and Jill went up the hill\n\n\t\tTo fetch a pail of water\n\n\t\tJack fell down and broke his crown\n\n\t\tAnd Jill came tumbling after\n '

In [8]:
token = Tokenizer()
token.fit_on_texts([data3])
encoded = token.texts_to_sequences([data3])[0]
#tokenizer.fit_on_texts(data2)
#encode1 = token.texts_to_matrix(data1, mode='count')

In [9]:
print(token.word_counts)

OrderedDict([('jack', 2), ('and', 3), ('jill', 2), ('went', 1), ('up', 1), ('the', 1), ('hill', 1), ('to', 1), ('fetch', 1), ('a', 1), ('pail', 1), ('of', 1), ('water', 1), ('fell', 1), ('down', 1), ('broke', 1), ('his', 1), ('crown', 1), ('came', 1), ('tumbling', 1), ('after', 1)])


In [10]:
token.document_count

1

In [11]:
token.word_index

{'and': 1,
 'jack': 2,
 'jill': 3,
 'went': 4,
 'up': 5,
 'the': 6,
 'hill': 7,
 'to': 8,
 'fetch': 9,
 'a': 10,
 'pail': 11,
 'of': 12,
 'water': 13,
 'fell': 14,
 'down': 15,
 'broke': 16,
 'his': 17,
 'crown': 18,
 'came': 19,
 'tumbling': 20,
 'after': 21}

In [12]:
token.word_docs

defaultdict(int,
            {'the': 1,
             'broke': 1,
             'went': 1,
             'crown': 1,
             'down': 1,
             'his': 1,
             'a': 1,
             'fell': 1,
             'fetch': 1,
             'jack': 1,
             'up': 1,
             'tumbling': 1,
             'after': 1,
             'hill': 1,
             'of': 1,
             'and': 1,
             'to': 1,
             'water': 1,
             'came': 1,
             'pail': 1,
             'jill': 1})

In [13]:
print(encoded)

[2, 1, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 2, 14, 15, 1, 16, 17, 18, 1, 3, 19, 20, 21]


In [14]:
vocab_size = len(token.word_index) + 1
print('Vocabulary Size: %d' % vocab_size)

Vocabulary Size: 22


In [15]:
sequences = list()

In [16]:
for i in range(1, len(encoded)):
	sequence = encoded[i-1:i+1]
	sequences.append(sequence)
print('Total Sequences: %d' % len(sequences))

Total Sequences: 24


In [17]:
sequences = np.array(sequences)
X, y = sequences[:,0],sequences[:,1]

In [18]:
X

array([ 2,  1,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13,  2, 14, 15,  1,
       16, 17, 18,  1,  3, 19, 20])

In [19]:
y

array([ 1,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13,  2, 14, 15,  1, 16,
       17, 18,  1,  3, 19, 20, 21])

In [20]:
y = to_categorical(y, num_classes=vocab_size)

In [21]:
y # One Hot Encoding

array([[0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.,

In [22]:
# define model
model = Sequential()
model.add(Embedding(vocab_size, 10, input_length=1))

In [23]:
model.add(Flatten())

In [24]:
model.add(Dense(vocab_size, activation='softmax'))
print(model.summary())

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 1, 10)             220       
_________________________________________________________________
flatten (Flatten)            (None, 10)                0         
_________________________________________________________________
dense (Dense)                (None, 22)                242       
Total params: 462
Trainable params: 462
Non-trainable params: 0
_________________________________________________________________
None


In [25]:
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
# fit network
model.fit(X, y, epochs=500, verbose=1)

Epoch 1/500
1/1 [==============================] - 2s 2s/step - loss: 3.0954 - accuracy: 0.0417
Epoch 2/500
1/1 [==============================] - 0s 6ms/step - loss: 3.0930 - accuracy: 0.0417
Epoch 3/500
1/1 [==============================] - 0s 6ms/step - loss: 3.0906 - accuracy: 0.0417
Epoch 4/500
1/1 [==============================] - 0s 6ms/step - loss: 3.0882 - accuracy: 0.0417
Epoch 5/500
1/1 [==============================] - 0s 5ms/step - loss: 3.0858 - accuracy: 0.0417
Epoch 6/500
1/1 [==============================] - 0s 5ms/step - loss: 3.0834 - accuracy: 0.0833
Epoch 7/500
1/1 [==============================] - 0s 6ms/step - loss: 3.0810 - accuracy: 0.1667
Epoch 8/500
1/1 [==============================] - 0s 6ms/step - loss: 3.0786 - accuracy: 0.1667
Epoch 9/500
1/1 [==============================] - 0s 6ms/step - loss: 3.0762 - accuracy: 0.1250
Epoch 10/500
1/1 [==============================] - 0s 5ms/step - loss: 3.0738 - accuracy: 0.1667
Epoch 11/500
1/1 [============

1/1 [==============================] - 0s 6ms/step - loss: 2.8447 - accuracy: 0.6250
Epoch 85/500
1/1 [==============================] - 0s 7ms/step - loss: 2.8404 - accuracy: 0.6250
Epoch 86/500
1/1 [==============================] - 0s 6ms/step - loss: 2.8361 - accuracy: 0.6250
Epoch 87/500
1/1 [==============================] - 0s 5ms/step - loss: 2.8318 - accuracy: 0.6250
Epoch 88/500
1/1 [==============================] - 0s 6ms/step - loss: 2.8275 - accuracy: 0.6250
Epoch 89/500
1/1 [==============================] - 0s 5ms/step - loss: 2.8231 - accuracy: 0.6250
Epoch 90/500
1/1 [==============================] - 0s 5ms/step - loss: 2.8187 - accuracy: 0.6250
Epoch 91/500
1/1 [==============================] - 0s 5ms/step - loss: 2.8142 - accuracy: 0.6250
Epoch 92/500
1/1 [==============================] - 0s 5ms/step - loss: 2.8097 - accuracy: 0.6250
Epoch 93/500
1/1 [==============================] - 0s 4ms/step - loss: 2.8052 - accuracy: 0.6667
Epoch 94/500
1/1 [===============

1/1 [==============================] - 0s 5ms/step - loss: 2.3760 - accuracy: 0.8333
Epoch 168/500
1/1 [==============================] - 0s 6ms/step - loss: 2.3691 - accuracy: 0.8333
Epoch 169/500
1/1 [==============================] - 0s 5ms/step - loss: 2.3622 - accuracy: 0.8333
Epoch 170/500
1/1 [==============================] - 0s 6ms/step - loss: 2.3553 - accuracy: 0.8333
Epoch 171/500
1/1 [==============================] - 0s 5ms/step - loss: 2.3483 - accuracy: 0.8333
Epoch 172/500
1/1 [==============================] - 0s 6ms/step - loss: 2.3413 - accuracy: 0.8333
Epoch 173/500
1/1 [==============================] - 0s 5ms/step - loss: 2.3343 - accuracy: 0.8333
Epoch 174/500
1/1 [==============================] - 0s 5ms/step - loss: 2.3273 - accuracy: 0.8333
Epoch 175/500
1/1 [==============================] - 0s 6ms/step - loss: 2.3203 - accuracy: 0.8333
Epoch 176/500
1/1 [==============================] - 0s 6ms/step - loss: 2.3133 - accuracy: 0.8750
Epoch 177/500
1/1 [=====

1/1 [==============================] - 0s 5ms/step - loss: 1.7692 - accuracy: 0.8750
Epoch 250/500
1/1 [==============================] - 0s 5ms/step - loss: 1.7617 - accuracy: 0.8750
Epoch 251/500
1/1 [==============================] - 0s 5ms/step - loss: 1.7542 - accuracy: 0.8750
Epoch 252/500
1/1 [==============================] - 0s 7ms/step - loss: 1.7467 - accuracy: 0.8750
Epoch 253/500
1/1 [==============================] - 0s 6ms/step - loss: 1.7392 - accuracy: 0.8750
Epoch 254/500
1/1 [==============================] - 0s 6ms/step - loss: 1.7318 - accuracy: 0.8750
Epoch 255/500
1/1 [==============================] - 0s 6ms/step - loss: 1.7243 - accuracy: 0.8750
Epoch 256/500
1/1 [==============================] - 0s 6ms/step - loss: 1.7168 - accuracy: 0.8750
Epoch 257/500
1/1 [==============================] - 0s 6ms/step - loss: 1.7094 - accuracy: 0.8750
Epoch 258/500
1/1 [==============================] - 0s 5ms/step - loss: 1.7019 - accuracy: 0.8750
Epoch 259/500
1/1 [=====

1/1 [==============================] - 0s 7ms/step - loss: 1.2057 - accuracy: 0.8750
Epoch 332/500
1/1 [==============================] - 0s 6ms/step - loss: 1.1998 - accuracy: 0.8750
Epoch 333/500
1/1 [==============================] - 0s 6ms/step - loss: 1.1939 - accuracy: 0.8750
Epoch 334/500
1/1 [==============================] - 0s 6ms/step - loss: 1.1880 - accuracy: 0.8750
Epoch 335/500
1/1 [==============================] - 0s 6ms/step - loss: 1.1821 - accuracy: 0.8750
Epoch 336/500
1/1 [==============================] - 0s 5ms/step - loss: 1.1763 - accuracy: 0.8750
Epoch 337/500
1/1 [==============================] - 0s 6ms/step - loss: 1.1704 - accuracy: 0.8750
Epoch 338/500
1/1 [==============================] - 0s 6ms/step - loss: 1.1647 - accuracy: 0.8750
Epoch 339/500
1/1 [==============================] - 0s 6ms/step - loss: 1.1589 - accuracy: 0.8750
Epoch 340/500
1/1 [==============================] - 0s 6ms/step - loss: 1.1532 - accuracy: 0.8750
Epoch 341/500
1/1 [=====

1/1 [==============================] - 0s 5ms/step - loss: 0.8102 - accuracy: 0.8750
Epoch 414/500
1/1 [==============================] - 0s 6ms/step - loss: 0.8065 - accuracy: 0.8750
Epoch 415/500
1/1 [==============================] - 0s 6ms/step - loss: 0.8028 - accuracy: 0.8750
Epoch 416/500
1/1 [==============================] - 0s 6ms/step - loss: 0.7992 - accuracy: 0.8750
Epoch 417/500
1/1 [==============================] - 0s 6ms/step - loss: 0.7955 - accuracy: 0.8750
Epoch 418/500
1/1 [==============================] - 0s 6ms/step - loss: 0.7919 - accuracy: 0.8750
Epoch 419/500
1/1 [==============================] - 0s 6ms/step - loss: 0.7884 - accuracy: 0.8750
Epoch 420/500
1/1 [==============================] - 0s 6ms/step - loss: 0.7848 - accuracy: 0.8750
Epoch 421/500
1/1 [==============================] - 0s 7ms/step - loss: 0.7812 - accuracy: 0.8750
Epoch 422/500
1/1 [==============================] - 0s 5ms/step - loss: 0.7777 - accuracy: 0.8750
Epoch 423/500
1/1 [=====

1/1 [==============================] - 0s 6ms/step - loss: 0.5770 - accuracy: 0.8750
Epoch 496/500
1/1 [==============================] - 0s 6ms/step - loss: 0.5749 - accuracy: 0.8750
Epoch 497/500
1/1 [==============================] - 0s 6ms/step - loss: 0.5728 - accuracy: 0.8750
Epoch 498/500
1/1 [==============================] - 0s 6ms/step - loss: 0.5707 - accuracy: 0.8750
Epoch 499/500
1/1 [==============================] - 0s 6ms/step - loss: 0.5687 - accuracy: 0.8750
Epoch 500/500
1/1 [==============================] - 0s 5ms/step - loss: 0.5666 - accuracy: 0.8750


In [26]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 1, 10)             220       
_________________________________________________________________
flatten (Flatten)            (None, 10)                0         
_________________________________________________________________
dense (Dense)                (None, 22)                242       
Total params: 462
Trainable params: 462
Non-trainable params: 0
_________________________________________________________________


# Text Prediction

In [27]:
n_words = 3
text_test = 'Jack'
result = 'Jack'

In [28]:
for _ in range(n_words):
    encoded = token.texts_to_sequences([text_test])[0]
    encoded = np.array(encoded)
    # predict a word in the vocabulary
    y_Predict = model.predict_classes(encoded, verbose=0)
    Next_word = ''
    for word, index in token.word_index.items():
        if index == y_Predict:
            Next_word = word
            break
    text_test, result = Next_word, result + ' ' + Next_word

C:\Users\Dr.PVVK\AppData\Roaming\Python\Python38\site-packages\tensorflow\python\keras\engine\sequential.py:455: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


In [29]:
print(result)

Jack and jill came
